# Generated by Django 3.2.7 on 2022-05-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
